config/routes.rb
VideoMarketing::Application.routes.draw do

  resources :videos
  get "/delayed_job" => DelayedJobWeb, :anchor => false

  get "/auth/:provider/callback" => "sessions#callback"
  get "/logout" => "sessions#destroy", :as => :logout
  get "/logon" => "sessions#new"
  post "/sessions/create" => "sessions#create"
  post "/login" => "sessions#login_attempt"

  root :to => "home#index"
  

  

end

app/models/user.rb
class User
	include Dynamoid::Document

  attr_accessor :password, :password_confirmation, :salt, :encripted_password
	
  field :name
  field :provider
  field :uid
  field :email
  field :encripted_password
  field :salt

  index :created_at, {:type=>:datetime}
  index :id, {:type=>:string}
  index :name, {:type=>:string}
  index :provider, {:type=>:string}
  index :uid, {:type=>:string}
  index :email, {:type=>:string}
  index :updated_at, {:type=>:datetime}

  validates :name, :presence => true, :length => { :in => 3..20 }
  validates_format_of :email, :with => /@/
  validates :password, :confirmation => true

  before_save :encrypt_password
  after_save :clear_password

  def encrypt_password
    if password.present?
      self.salt = BCrypt::Engine.generate_salt
      self.encripted_password = BCrypt::Engine.hash_secret(password, salt)
      self.provider = "videomarketing"
    end
  end

  def clear_password
    self.password = nil
  end

  def self.create_with_omniauth(auth)
    create!(
      :name     => auth["info"]["nickname"],
      :provider => auth["provider"],
      :uid      => auth["uid"],
      :email    => auth["uid"]
    )
  end

  def self.authenticate(email="", login_password="")
    user = User.find_by_email(email)
    if user && user.match_password(login_password, user.encripted_password)
      return user
    else
      return false
    end
  end

  def match_password(login_password="", enc_password="")
    enc_password == BCrypt::Engine.hash_secret(login_password, salt)
  end

	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	#attr_accessible :nombre, :apellidos, :email, :password, :password_confirmation
	
	#devise :database_authenticatable, :registerable,
	#	   :recoverable, :rememberable, :trackable, :validatable
end

app/models/video.rb
class Video
  include Dynamoid::Document

	#mount_uploader :video, VideoUploader
	#mount_uploader :video_converted, VideoConvertedUploader

  table :name => :videos, :read_capacity => 10, :write_capacity => 10

  field :video_url
  field :message
  field :converted_at, :datetime
  field :state
  field :video_converted_url
  field :converted_finished_at, :datetime
  field :email

	validates :message, :presence => true
	validates :state, :presence => true
	validates :video_url, :presence => true
	email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, :presence => true, :format => { :with => email_regex }

	#scope :converted, where('videos.converted_finished_at IS NOT NULL')
	#scope :ordered_desc_by_created_at, order('videos.created_at DESC')

	PROCESSING_STATE = 0
	CONVERTED_STATE = 1

	after_save :convert_video

	def convert_video
		self.delay.process_video
	end

	def process_video
		puts 'Convirtiendo video...'
		if self.converted_at.nil?
			self.converted_at = Time.zone.now

			video_url = Rails.root.join("public/uploads/video/video/#{DateTime.now}")
			Dir.mkdir(video_url)
			video_url = video_url.to_s() + "/" + self.video_url.split('/').last
			open(video_url, 'wb') do |file|
				file << open(self.video_url).read
			end
			puts 'Video url: '+video_url

			movie = FFMPEG::Movie.new(video_url)
			options = {video_codec: "libx264"}
			video_name = self.video_url.split('/').last
			video_converted_url = "#{Rails.root}/tmp/converted_#{UUIDTools::UUID.random_create.hexdigest}_"+video_name[0,video_name.size-4]+'.mp4'
			puts 'Converted url: '+video_converted_url
			movie.transcode(video_converted_url, options)

			uploaderConverted = VideoConvertedUploader.new
			if uploaderConverted.store!(File.open(video_converted_url))
				self.video_converted_url = uploaderConverted.url
				self.state = CONVERTED_STATE
				self.converted_finished_at = Time.zone.now
				if self.save
					File.delete(video_converted_url)
				end
			end
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  private
  def current_user
    if session[:user_id]
      @current_user = User.find(session[:user_id])
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@videos = Video.where(:state => Video::CONVERTED_STATE.to_s()).all
		@video = Video.new
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def callback
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_url, :notice => "Sesión de usuario iniciada."
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Sesión de usuario terminada."
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "Registro exitoso"
    else
      flash[:notice] = "Formulario inválido"
    end
    session[:user_id] = @user.id
    redirect_to root_url, :notice => "Registro exitoso."
  end

  def login
  end

  def login_attempt
    authorized_user = User.authenticate(params[:user][:email],params[:user][:login_password])
    if authorized_user
      session[:user_id] = authorized_user.id
      flash[:notice] = "Bienvenido(a) #{authorized_user.name}"
    else
      flash[:notice] = "Nombre de usuario o contraseña inválidos"
    end
    redirect_to root_url
  end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_filter :authenticate

  def authenticate
    redirect_to :login unless current_user
  end
  
  def new
    @video = Video.new
  end

  def create
    uploader = VideoUploader.new
    if uploader.store!(params[:video][:video])
      @video = Video.new
      @video.message = params[:video][:message]
      @video.email = params[:video][:email]
      @video.video_url = uploader.url
      @video.state = Video::PROCESSING_STATE
      if @video.save
        flash[:success] = 'Hemos recibido el video, pronto lo revisaremos y publicaremos. Gracias por participar en el concurso.'
        redirect_to root_path
      else
        flash[:error] = 'Error cargando el video.'
        render 'new'
      end
    end
  end

  def index
    @videos = Video.where(:email => current_user.email).all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def resource_name
		:user
	end

	def resource
		@resource ||= User.new
	end

	def devise_mapping
		@devise_mapping ||= Devise.mappings[:user]
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/home/index.html.haml
.jumbotron
	.container
		%h1 Suba un video usando nuestro producto
		%h3 ¡Participe subiendo un video en el que use nuestros productos! Los tres mejores videos ganarán fabulosos premios.
.container
	.row
		.col-lg-12
			- flash.each do |key, value|
				.alert{:class => "#{key.to_s == 'error' ? key : 'info'}"}
					%strong
						= value
	.row
		.col-lg-9
			%h2 Videos actuales
			- @videos.each do |video|
				%div{id: "myElement#{video.id}"} Cargando el reproductor...
				:javascript
					jwplayer("myElement#{video.id}").setup({file: "rtmp://s2s05p0x276k5a.cloudfront.net/cfx/st/mp4:#{video.video_converted_url.split('/').last}", width: 640, height: 480, title: "#{video.message}"});
				%p= video.message
		.col-lg-3
			- if current_user
				%h4 Sube tu video
				= form_for(@video, :url => videos_path, :method => :post, :html => {:multipart => true, :class => "form-horizontal", :role => "form" }) do |f|
					.form-group
						= f.hidden_field :email, :value => current_user.email
						= f.label :message, "Mensaje *"
						= f.text_field :message, :maxlength=> 100, :class => "form-control", :required => true
					.form-group
						= f.label :video, "Video *"
						= f.file_field :video
					.form-group= f.submit "Enviar"
			- else
				%h2 Iniciar sesión
				= form_for(resource, :as => resource_name, :url => "/login") do |f|
					%div
						= f.label :email, "Email *"
						%br/
						= f.email_field :email, :autofocus => true
					%div
						= f.label :login_password, "Contraseña *"
						%br/
						= f.password_field :login_password
					%div= f.submit "Iniciar sesión"
				= link_to("Registrarse", '/logon', method: :get)

app/views/layouts/application.html.haml
!!!
%html
	%head
		%title Video Marketing APP

		%meta{name: "viewport", content: "width=device-width, initial-scale=1.0"}

		/ Boostrap Latest compiled and minified CSS
		%link{:href => "//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css", :rel => "stylesheet"}

		= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
		= javascript_include_tag "application", "data-turbolinks-track" => true
		= javascript_include_tag 'jwplayer/jwplayer.js', :media => 'screen'
		= javascript_include_tag 'jwplayer/jwplayer.html5.js', :media => 'screen'

		/ Boostrap Latest compiled and minified JavaScript
		%script{:src => "//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"}

		= csrf_meta_tags
	%body
		/ Header navbar
		%navbar.navbar-default{role: "navigation"}
			.navbar-header
				%a.navbar-brand Video Marketing APP
			.collapse.navbar-collapse.navbar-ex1-collapse
				%ul.nav.navbar-nav
					%li
						= link_to("Home", root_path) unless current_page?(root_url)
					%li
						= link_to("Videos publicados", { :controller => "videos", :action => "index" }) unless !current_user
				%ul.nav.navbar-nav.navbar-right
					%li
						- if current_user
							= link_to("Cerrar sesión", '/logout', method: :get)
						- else
							= link_to("Iniciar sesión con Twitter", '/auth/twitter', method: :get)
		= yield

app/views/videos/index.html.haml
.container
	.row
		.col-lg-12
			%table.table
				%thead
					%tr
						%th ID
						%th Email
						%th Message
						%th State
						%th Video URL
						%th Fecha creación
						%th Fecha inicio conversión
						%th Fecha fin conversión
						%th Video Converted URL
				%tbody
					- @videos.each do |video|
						%tr
							%td= video.id
							%td= video.email
							%td= video.message
							%td= video.state
							%td= video.video_url
							%td= video.created_at
							%td= video.converted_at
							%td= video.converted_finished_at
							%td= video.video_converted_url

app/views/videos/new.html.haml
.container
  .row
    .col-lg-12
      = form_for(@video, :url => videos_path, :method => :post, :html => {:multipart => true, :class => "form-horizontal", :role => "form" }) do |f|
        = f.hidden_field :email, :value => current_user.email
        .form-group
          = f.label :message, "Mensaje *"
          = f.text_field :message, :maxlength=> 100, :class => "form-control", :required => true
        .form-group
          %label{:for => "exampleInputFile"} File input
          = f.label :video, "Video *"
          = f.file_field :video
          %p.help-block Example block-level help text here.
        %button.btn.btn-default{:type => "submit"} Enviar